gpu_id: 0
multi_gpus : False
num_workers: 4
seed: 666
exp_name: 'NEXT_QA_Action'

model:
  num_head: 8
  word_dim: 300
  module_dim: 512
  vision_dim: 2048

train:
  lr: 0.0001
  glove: True

dataset:
  name: 'next-qa'
  question_type: 'action'